services:
  patient-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-service
    ports:
      - "8081:8081"
    environment:
      # Connects to Postgres on your host machine
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/patient_db
      # Connects to Billing Service on your host machine
      - BILLING_SERVICE_ADDRESS=host.docker.internal
      - BILLING_SERVICE_GRPC_PORT=9001
    extra_hosts:
      - "host.docker.internal:host-gateway"


# To run the services, use the command:
# docker-compose up --build -d